In [2]:
# Identity, Zero, Diagonal, triangular(Upper, Lower)


from numpy import eye, identity, zeros, diag

a = eye(4)
print(a, 'eye')


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] eye


In [3]:
b = identity(4)
print(a, 'identity')


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] identity


In [4]:
c = zeros((4, 4))
print(c, 'zeros')


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] zeros


In [5]:
d = diag([1, 5, 1, 2, 3, 1])
print(d, 'diag')
print()
print(d.diagonal())

[[1 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 1]] diag

[1 5 1 2 3 1]


In [6]:
from matplotlib.pyplot import *
from numpy import random, triu, tril

e = random.random((10, 10))

fig, ax = subplots(1, 3, figsize=(8, 5))
ax[0].imshow(tril(e))
ax[1].imshow(e)
ax[2].imshow(triu(e))

for axi in ax:
    axi.axis('off')
show()

In [7]:
from numpy import eye, triu, random

rm = random.randint(-4, 5, (4, 4))
I = eye(4, dtype=int)

print(rm, "rm")
print()
print(rm*I, "rm*I")
print()

print(rm@I, "rm@I")



[[ 2 -3 -3  0]
 [ 0 -4  2  3]
 [-3 -3  4  1]
 [ 4  4  3  2]] rm

[[ 2  0  0  0]
 [ 0 -4  0  0]
 [ 0  0  4  0]
 [ 0  0  0  2]] rm*I

[[ 2 -3 -3  0]
 [ 0 -4  2  3]
 [-3 -3  4  1]
 [ 4  4  3  2]] rm@I


In [8]:
rm2 = random.randint(-4, 5, (4, 4))
tm = triu(rm2)

print(tm)
print(rm*tm)

[[-1  0 -1  2]
 [ 0 -1 -4 -3]
 [ 0  0  2  4]
 [ 0  0  0  4]]
[[-2  0  3  0]
 [ 0  4 -8 -9]
 [ 0  0  8  4]
 [ 0  0  0  8]]


In [12]:
from numpy import zeros, arange

def create_toeplitz(lst1, lst2=None):
    length = len(lst1)

    if lst2 is None:
        z = zeros((length, length), dtype=int)
        for i in range(length):
            for j in range(i, length):
                z[i, j] = lst1[j - i]
        return z + z.T - z*eye(length, dtype=int)

    elif len(lst2) != length or lst1[0] != lst2[0]:
        raise ValueError("list langth must be equal, or list's first value must be same")

    else:
        z1 = zeros((length, length), dtype=int)
        z2 = zeros((length, length), dtype=int)

        for i in range(length):
            for j in range(i, length):
                z1[i, j] = lst1[j - i]
                z2[i, j] = lst2[j - i]

        return z1 + z2.T - z1*eye(length, dtype=int)

toe1 = create_toeplitz([1, 4, 2, 3], [1, 7, 4, 5])
toe2 = create_toeplitz(arange(1,10))

imshow(toe2)
show()

In [10]:
from scipy.linalg import toeplitz
toe3 = toeplitz(arange(1,10))
print()
print(toe3)


[[1 2 3 4 5 6 7 8 9]
 [2 1 2 3 4 5 6 7 8]
 [3 2 1 2 3 4 5 6 7]
 [4 3 2 1 2 3 4 5 6]
 [5 4 3 2 1 2 3 4 5]
 [6 5 4 3 2 1 2 3 4]
 [7 6 5 4 3 2 1 2 3]
 [8 7 6 5 4 3 2 1 2]
 [9 8 7 6 5 4 3 2 1]]
